backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/book-covers/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/public" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "Books" # Used in routes, e.g., /admin/collections/books
    label: "Books" # Used in the UI
    folder: "src/content/books" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../src/layouts/BookReview.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "BookAuthor", name: "bookAuthor", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "HeroImage", name: "heroImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "AffiliateLink", name: "affiliateLink", widget: "string", required: false}
      - {label: "YouTubeLink", name: "youTubeLink", widget: "string", required: false}
      - {label: "SpotifyLink", name: "spotifyLink", widget: "string", required: false}
      - {label: "SpotifyEmbedURL", name: "spotifyEmbedURL", widget: "string", required: false}
      - {label: "ApplePodcastsLink", name: "applePodcastsLink", widget: "string", required: false}
      - {label: "ApplePodcastsEmbedURL", name: "applePodcastsEmbedURL", widget: "string", required: false}